### ISSUE TITLE
Preference Pane Appears off Center on iPads

### ISSUE THREAD

**Issue by ReddestDream** [evilGoldfish/LockGlyph#7]
See pictures:

<img width="768" alt="wm3keqa" src="https://cloud.githubusercontent.com/assets/4013634/10560873/df39fac8-74e5-11e5-8b2a-d72346f6ce77.png">

<img width="1024" alt="rmqb4az" src="https://cloud.githubusercontent.com/assets/4013634/10560880/2495564e-74e6-11e5-940c-3986aadfd2b0.png">

I can help you test your tweak on iPads if you would like! Thanks! ^_^

**Comment by evilGoldfish** [comment]
Thanks! This has been fixed with the latest commit.

**Comment by ReddestDream** [comment]
Thank you! ^_^
