### ISSUE TITLE
Glyph appears off-screen on iPads in Landscape

### ISSUE THREAD

**Issue by ReddestDream** [evilgoldfish/LockGlyph#9]
Unfortunately, it seems this issue is still not fixed on my iPad Pro with the latest version (1.1.12-3).

The Glyph is still offscreen by default in Landscape . . . :(

I can pull it back with custom landscape settings, but it still not in the middle, rather shifted to one side . . .

**Comment by evilgoldfish** [comment]
I jailbroke my iPad and discovered the same issue, unfortunately. going to have to investigate more.
